#!/bin/sh

# key repeat instead of that accent character menu.
defaults write -g ApplePressAndHoldEnabled -bool false

## Finder

# Show hidden files.
# defaults write com.apple.finder AppleShowAllFiles YES
defaults write -g AppleShowAllFiles -bool true

# Show all extensions.
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Disable the warning when changing a file extension.
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Always open everything in Finder's column view
defaults write com.apple.Finder FXPreferredViewStyle clmv

# Allow selection of text in quicklook windows.
defaults write com.apple.finder QLEnableTextSelection -bool true

# Show status bar.
defaults write com.apple.finder ShowStatusBar -bool true

# Show path bar.
defaults write com.apple.finder ShowPathbar -bool true

# Disable warning when the user does empty trash.
defaults write com.apple.finder WarnOnEmptyTrash -bool false


## Dock

# Move Dock to the right side of the screen
defaults write com.apple.dock "orientation" -string "right" && killall Dock
